#!/bin/bash


# Allow __git_ps1 to work on arch linux
[[ -f /usr/share/git/git-prompt.sh ]] && . /usr/share/git/git-prompt.sh

GIT_PS1_SHOWDIRTYSTATE=1
GIT_PS1_SHOWSTASHSTATE=1
GIT_PS1_SHOWUNTRACKEDFILES=1

get_ps1() {
    local blue="\[\033[0;34m\]"
    local white="\[\033[0;00m\]"
    local magenta="\[\033[0;35m\]"
    local pink="\[\033[0;31m\]"
    local green="\[\033[0;32m\]"

    local user="${blue}\u${white}"
    local host="${hostname}\h${white}"
    local dir="${green}\w${white}"
    local time="${green}\$(date \"+%H:%M:%S\")${white}"

    local git="${white}\$(__git_ps1 '%s')${white}"

    echo "${user}@${host} ${dir} ${git}\n${time} $ "
}

PS1="$(get_ps1)"

export GOPATH=$HOME/go

# Increase the amount of history bash will store and reload
export HISTFILE=~/.history
export HISTSIZE=
export HISTFILESIZE=
# Allows for sharing of history across tmux session
# "-a" immediately appends new history to the histfile
export PROMPT_COMMAND='history -a'
# Ignore and erase duplicates and commands with leading whitespace
export HISTCONTROL=ignoreboth:erasedups

export EDITOR=vim

# ipython needs these two
export PAGER=less
export less=-r

# Platform dependant stuff
if [[ "$(uname)" == 'Linux' ]]; then
    . ~/.bash_linux
elif [[ "$(uname)" == 'Darwin' ]]; then
    . ~/.bash_mac
fi

export PATH="$HOME/bin:$HOME/go/bin:$PATH"

export PYTHONDONTWRITEBYTECODE=1

eval "$(${HOME}/.local/bin/mise activate bash)"
source <(mise completion bash)

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/cameron/google-cloud-sdk/path.bash.inc' ]; then . '/Users/cameron/google-cloud-sdk/path.bash.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/cameron/google-cloud-sdk/completion.bash.inc' ]; then . '/Users/cameron/google-cloud-sdk/completion.bash.inc'; fi
