# The current version of the config schema
version: 1
# What protocol to use when performing git operations. Supported values: ssh, https
git_protocol: https
# What editor gh should run when creating issues, pull requests, etc. If blank, will refer to environment.
editor:
# When to interactively prompt. This is a global config that cannot be overridden by hostname. Supported values: enabled, disabled
prompt: enabled
# Preference for editor-based interactive prompting. This is a global config that cannot be overridden by hostname. Supported values: enabled, disabled
prefer_editor_prompt: disabled
# A pager program to send command output to, e.g. "less". If blank, will refer to environment. Set the value to "cat" to disable the pager.
pager:
# Aliases allow you to create nicknames for gh commands
aliases:
  co: pr checkout
  prt: '!gh pr list --json number,title,additions,deletions,isDraft,author,headRefName,baseRefName | jq -r ''def truncate(str; max): if (str | length) > max then str[0:max-3] + "..." else str end; "PR#\tTitle\tStatus\tAuthor\tBranch\t+Add\t-Del", "---\t-----\t------\t------\t------\t----\t----", (.[] | "\(.number)\t\(truncate(.title; 50))\t\(if .isDraft then "DRAFT" else "Ready" end)\t\(truncate(.author.login; 15))\t\(truncate(.headRefName; 25))→\(.baseRefName)\t+\(.additions)\t-\(.deletions)")'' | column -t -s $''\t'''
# The path to a unix socket through which send HTTP connections. If blank, HTTP traffic will be handled by net/http.DefaultTransport.
http_unix_socket:
# What web browser gh should use when opening URLs. If blank, will refer to environment.
browser:
# Whether to display labels using their RGB hex color codes in terminals that support truecolor. Supported values: enabled, disabled
color_labels: disabled
# Whether customizable, 4-bit accessible colors should be used. Supported values: enabled, disabled
accessible_colors: disabled
# Whether an accessible prompter should be used. Supported values: enabled, disabled
accessible_prompter: disabled
# Whether to use a animated spinner as a progress indicator. If disabled, a textual progress indicator is used instead. Supported values: enabled, disabled
spinner: enabled
