[settings]
experimental = true
idiomatic_version_file_enable_tools = ["python"]

[tools]
bun = "latest"
neovim = "latest"
node = "22.12.0"
prettier = "latest"
python = "3.12"
usage = "latest"
uv = "latest"
